spring:
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:productdb
      driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

---

spring:
  profiles: default
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:productdb
      driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

test:
  name: My-boot-new

---

spring:
  profiles: product
  h2:
    console:
      enabled: true
    datasource:
      url: jdbc:h2:mem:productdb
      driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
